Sandbox
java-park-mail-ru/TaradosFeroces-02-2018 pull request #1
Opened 2018-02-28 09:35 UTC by Alex-Kuz

Registration without database : hashmap (implements UserDAO interface).

2018-02-28 11:09 UTC, isopov commented
Какое странное название PR - его можно проверять уже?

2018-02-28 11:35 UTC, isopov commented
1. Что такое deadlines? Мы тут путаемся, и очень просим вас делать одинаковыми имя проекта и команды
```
	<groupId>tarados-feroces</groupId>
	<artifactId>deadlines</artifactId>
```
2. UserSignInRequest - и для выших фронтендеров это удобное API? 0_0
3. Кстати в двух Request-ах из трех поля нефинальные почему-то.
4. В контроллере вместо raw-типа ResponseEntity можно использовать `ResponseEntity<Message>` или `ResponseEntity<?>`  где нельзя первое.
5. Почему закомментирован код, который по идее нужен?
```
/*(origins = {"http://tf-sand-server.herokuapp.com/", "localhost"})*/
...
// httpSession.setAttribute(USER_ID, id);
```
Если не прописаны конкретные разрешения на CORS, то не получится сделать логин, AFAIK
6. Вместо
```
    @Bean
    public UserDAO userDAO() {
        return new UserDAOImplRunTime();
    }
```
Можно просто пометить UserDAOImplRunTime аннотацией `@Component` или какой-нибудь производной. Впрочем, это пока дело вкуса и почти всё равно. А вот когда у этого класса появятся зависимости - через аннотацию точно будет проще и короче.
7. Зависимостей как-то многовато неиспользуемых - если что-то пробуете, удаляйте потом то, что не распробовали - spring-boot-starter-data-jpa, spring-boot-starter-data-rest, spring-boot-starter-jdbc (эта кстати приходит вместе с spring-boot-starter-data-jpa), spring-security-core (плюс за то, что смотрите в эту сторону;-)), postgresql & h2 - ну и где использование всего этого? ))
8. Неиспользуемых методов лучше не оставлять - UserDAO.clear, UserDAO.deleteUser, UserDAO.updatePassword.
9. Кстати, к полям класса можно обращаться и без ключевого слова `this`, если их не перекрывают никакие локальные переменные.
10. Вот этот код 
```
       if (this.users.containsKey(id)) {
            return this.users.get(id);
        }
        return null;
```
можно заменить просто на `return this.users.get(id);`
11. В `.gitignore` как-то много мусора. Чтобы не было неожиданностей, лучше оставлять только то, что в репозитории (хотя бы теоретически) может появиться, и с результатами сборки быть конкретнее - игнорировать только target, а если класс-файлы или другие артефакты сборки появятся в других местах сразу видеть их в `git diff`-е и понимать, что что-то идёт не так.

2018-02-28 11:35 UTC, isopov requested changes
Замечания в комментарии.

2018-02-28 12:55 UTC, Alex-Kuz commented
1) *Deadlines* - название нашего проекта. Если необходимо переимновать - то переименую.
7) Разве необходимо было уже прикрутить БД?

2018-02-28 13:12 UTC, isopov commented
@Alex-Kuz 

> Deadlines - название нашего проекта. Если необходимо переимновать - то переименую.

мы путаемся, если на одну команду/проект получается больше одного названия - тратится время на постоянное переключение в табличку для поиска соответствие, поэтому уже пару семестров просим иметь только одно название 

> Разве необходимо было уже прикрутить БД?

БД не надо было - а у вас какие-то её части уже в проекте есть.

2018-02-28 16:43 UTC, Alex-Kuz commented
Исправил ошибки

2018-03-07 08:09 UTC, isopov commented
Прошу прощения за задержку.
1. Почему вы перешли на работу с coockie самописную вместо сессии?
2. В spring-boot версии большинства зависимостей управляются spring-boot-ом. Вручную версию стоит писать только для того, что не управляется, или если нужно переопределить версию зависимости с какой-то конкретной целью - эту цель стоит писать в комментарии рядом с переопределением. В этом случае, скорее всего ни то, ни другое - а просто версию надо убрать
```
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-core</artifactId>
            <version>4.2.2.RELEASE</version>
        </dependency>
```
3. `<version>1.5.10.RELEASE</version>` - на этот РК можно оставить, но в будущем надо перейти на 2.0.0.RELEASE (или более позднюю, если она уже выйдет) - чисто для удобства, когда начнем работать с тестам, БД, вебсокетами (и может вы что-то еще захотите добавить в проект) там появятся маленькие несовместимости между двумя мажорными версиями, и проще будет, если все будут делать на одной
4. `oraclejdk8` - опять же, пока можно оставить так, но мы просим java9 (а 20 марта выйдет релиз java10 уже)
5.  Не хотите удалить неиспользуемые методы из UserDAO? - вам его потом переписывать на другие технологии.

2018-03-09 09:36 UTC, isopov commented
И кстати - про безопасность у вас будет курс в следующем семестре, но обычно ошибки "неправильный login" и "неправильный пароль" должны быть одинаковыми, чтобы нельзя было перебором подобрать список существующих login-ов в системе.

2018-04-08 13:50 UTC, KSolovyev commented
Как дела?

2018-04-08 19:16 UTC, Alex-Kuz commented
~~отстой, переход на jdk9 был болезненным~~ нормально. Можно проверять. Извините за задержку

2018-04-09 19:32 UTC, Alex-Kuz commented
Было бы очень здорово наконец перейти ко второму рк.

2018-04-10 20:37 UTC, Alex-Kuz commented
Так, я не сильно понимаю текущую ситуацию с этим ПР.

2018-04-14 07:25 UTC, isopov commented
Из оставшегося, что можете пофиксать, но я уже проверять не буду.
- `System.out.println()` - не надо использовать и в тестах тоже. (Логирование я бы тоже не использовать - главные сообщения тесты должны давать AssertionError-ами)
- закоментированный код - мусор и стоит удалять. Временно неработающие тесты можно помечать аннотацией `@Ignore`
- кстати, тесты мы от вас требуем на Junit5 (хотя бы для единообразия, чтобы у всех были одинаковые проблемы)
- `application.utils.omgjava.Pair` - это действительно OMG, и не нужно. Вместо кучи статусов можно использовать один - успешный и исключения для 
```
USER_NOT_EXISTS,
        EMAIL_CONFLICT,
        LOGIN_CONFLICT,
        EMAIL_AND_LOGIN_CONFLICT,
        DB_ERROR
```
- пересмотрите методы, которые Идеей подсвечиваются, как неиспользуемые - если они такими и останутся - удалите.
- h2 у вас в compile scope (должна быть в тестовом, если вы ей в тестах пользуетесь - вы с проблемами можете и не встретиться, но в реальных проектах лучше использовать в тестах ту же базу, что и на бою)
- gson зачем-то указан с версией - но его версия в spring-boot тоже управляется. И если он используется только в тестах, то scope=test
- maven-compiler-plugin - этот конфиг вручную вам не нужен, должно хватить только свойства - `<java.version>9</java.version>`
- postgresql - тоже указана версия и уже довольно старая. в 2.0.1 буте сильно новее
- flyway-maven-plugin мы тоже не рекомендуем - очень вероятно что и вам он тоже не нужен.
- spring-data-commons - совсем непонятно, зачем эта зависимость.
- `<version>1.0.0</version>` - версия вашего проекта в pom.xml - к ней стоит добавить `-SNAPSHOT` - это значит, что под одной и той же снапшотной версией будет физически разный код. Фиксированные версии могут кешироваться в разных системах. Даже если сейчас вы не столкнетесь с проблемами, лучше сразу делать хорошо.
- `DROP TABLE IF EXISTS users CASCADE` - в миграции это плохо по несколькими причинам
        - по-умолчанию flyway стартует только на пустой схеме и если бы там была табличка - он бы накатывать миграцию не стал
       -  даже когда вы стартуете систему мигации не в дефолтном режиме, стоит контроллировать схему, которая была до системы миграций и если что-то расходится с вашими ожиданиями - применять подход fail fast. Одним словом IF EXISTS в норме в миграциях БД использовать не стоит.

2018-04-14 07:25 UTC, merged