RK2
java-park-mail-ru/TaradosFeroces-02-2018 pull request #3
Opened 2018-04-26 17:27 UTC by Alex-Kuz

2018-05-02 16:49 UTC, KSolovyev requested changes
а что с travis CI?

2018-05-02 16:49 UTC, KSolovyev commented on src/test/java/application/controllers/UserControllerTest.java
> +    /*
?

2018-05-02 16:49 UTC, KSolovyev commented on src/main/java/application/services/AuthService.java
> +        /*
?

2018-05-02 16:51 UTC, KSolovyev commented
Dockerfile не хватает. Без него вряд ли заработает. И надо вытаскивать базу из образа. Это совсем не дело пихать ее туда

2018-05-02 18:31 UTC, Alex-Kuz commented
Убрал докер
Купил тачку и домен - теперь на нем будем хоститься. Пока без автоматического деплоя. Пока что.
На хероку постоянно заканчиваются диносы, которые отвечают за количество запросов (так как у меня самые крутые фронтендеры, без сарказма, реально лучшие).

2018-05-02 18:32 UTC, Alex-Kuz commented
Тесты теперь работают, хоть их и мало
Жаль, что пришлось работать без докера.

2018-05-02 18:34 UTC, Alex-Kuz commented
А, ну да
У Вас (В Вашем трэвисе) тесты и не будут проходить, так как нет соответсвующих переменных окружения
Сейчас добавлю костыль, чтобы обойти это.

2018-05-02 18:45 UTC, adkuz commented
Странно. Я не понимаю, в чем сейчас ошибка.

2018-05-02 18:56 UTC, adkuz commented
Вот теперь можно проверять

2018-05-02 19:46 UTC, KSolovyev requested changes

2018-05-02 19:46 UTC, KSolovyev commented on src/main/java/application/dao/implementations/UserDAOImpl.java
> +            System.out.println("\n\n\n###USER_DAO: " + ex.toString() + "\n\n\n");
исключения надо логировать через логгер

2018-05-02 19:46 UTC, KSolovyev commented on src/main/java/application/dao/implementations/UserDAOImpl.java
> +            final String query = "SELECT * FROM users WHERE email = ?";
код одинаковый для 3-х функций. Надо общую часть

2018-05-02 19:46 UTC, KSolovyev commented on src/main/java/application/dao/implementations/UserDAOImpl.java
> +                query += "login = \'" + data.get("login").toString() + "\'";
вот тут будет sql injection

2018-05-02 19:46 UTC, KSolovyev commented on src/main/java/application/dao/implementations/UserDAOImpl.java
> +    public UpdateStatus updateUser(@NotNull long userId, @NotNull Map<String, ? extends Object>  data) {
нет особого смысла писать `? extends Object`. Можно просто Object

2018-05-02 19:46 UTC, KSolovyev commented on src/main/java/application/dao/implementations/UserDAOImpl.java
> +            LOGGER.error("DuplicateKeyException in updateUser");
`LOGGER.error("DuplicateKeyException in updateUser", e);`

2018-05-02 19:46 UTC, KSolovyev commented on src/main/java/application/dao/implementations/UserDAOImpl.java
> +            LOGGER.error("DuplicateKeyException in updateUser");
И везде добавьте исключение

2018-05-02 19:46 UTC, KSolovyev commented on src/test/java/application/controllers/UserControllerTest.java
> +        accountService.deleteAllUsers();
а зачем нужно это, если тесты `@Transactional` ?

2018-05-02 19:46 UTC, KSolovyev commented on src/main/java/application/dao/implementations/UserDAOImpl.java
> +    public UserScore updateScore(@NotNull Long id, @NotNull Long newScore) {
Не используется

2018-05-02 19:46 UTC, KSolovyev commented on src/main/java/application/services/AccountService.java
> +                return new Pair<>(UpdateStatus.EMAIL_AND_LOGIN_CONFLICT, null);
вот тут прям напрашивается список ошибок. Но это, если захотите

2018-05-02 19:59 UTC, Alex-Kuz commented on src/main/java/application/services/AccountService.java
> +                return new Pair<>(UpdateStatus.EMAIL_AND_LOGIN_CONFLICT, null);
Конечно же, хочу

2018-05-21 19:23 UTC, KSolovyev commented
@Alex-Kuz как дела? Надо закрывать уже =(

2018-05-23 07:02 UTC, Alex-Kuz commented
Я добавил тестов
Но в другой ветке, которую придется влить в эту, чтобы не перекидывать ПР.

2018-05-23 07:15 UTC, Alex-Kuz commented
пришлось руками переносить из приватного репозитория в этот, ибо только так можно кинуть ПР.

2018-05-23 07:17 UTC, Alex-Kuz commented
Добавил тестов: теперь они покрывают AccountService и FriendsService  (то есть все равно перед добавлением друга, его нужно создать, и делается это в одном блоке тестов); немного подправил UserDAOPostgres.

2018-05-23 07:28 UTC, Alex-Kuz commented
Вот теперь готово.

2018-05-27 10:22 UTC, KSolovyev requested changes

2018-05-27 10:22 UTC, KSolovyev commented on src/main/java/application/controllers/FriendsController.java
> +        return null;
В userService у вас все ошибки расписаны, а тут почему-то всегда null. Как пользователю-то узнать, что что-то пошло не так

2018-05-27 10:22 UTC, KSolovyev commented on src/main/java/application/controllers/FriendsController.java
> +        if (allFriendsOfUser == null || allFriendsOfUser.size() == 0) {
`allFriendsOfUser.isEmpty()`

2018-05-27 10:22 UTC, KSolovyev commented on src/main/java/application/controllers/FriendsController.java
> +            return ResponseEntity.status(HttpStatus.FORBIDDEN)
Forbidden - это не хватает прав, чтобы добавить пользователя. А здесь пользователя такого нет. Это 400 Bad request

2018-05-27 10:22 UTC, KSolovyev commented on src/main/resources/db/migration/V0013__init.sql
> +
Странно, что у вас миграции начинаются с 13 номера. Где все остальные-то?

2018-05-27 10:22 UTC, KSolovyev commented on src/main/resources/db/migration/V0013__init.sql
> +    id2 bigint references users(id)
вот тут нужен unique constraint на эти два поля

2018-05-27 10:22 UTC, KSolovyev commented on src/main/resources/db/migration/V0013__init.sql
> +    friend bigint references users(id)
и тут

2018-05-27 10:22 UTC, KSolovyev commented on src/main/java/application/dao/implementations/FriendsDAOPostgres.java
> +    public Id<User> deleteFriendshipRequest(long requestId, long friendId) {
вот это надо делать только в транзакции

2018-05-27 10:22 UTC, KSolovyev commented on src/main/java/application/dao/implementations/FriendsDAOPostgres.java
> +        final String query = "INSERT INTO friends(id1, id2) VALUES (?,?), (?,?);";
я бы сказал, что вот здесь надо сортировать идентификаторы

2018-05-27 10:22 UTC, KSolovyev commented on src/main/java/application/dao/implementations/FriendsDAOPostgres.java
> +                        + "WHERE f.id1 = ? AND LOWER(login) LIKE '" + friendNamePrefix + "%' ORDER BY LOWER(login);";
на Lower(login) нужен индекс

2018-05-27 10:22 UTC, KSolovyev commented on src/main/java/application/mechanics/game/GameObject.java
> +public abstract class GameObject {
а давайте мы все про механику отправим в следующий пул реквест

2018-05-27 18:33 UTC, Alex-Kuz commented on src/main/resources/db/migration/V0013__init.sql
> +
Я их не сохранял. Сейчас уже 15 версия. Начиная с этой, буду сохранять.

2018-05-27 18:33 UTC, adkuz commented on src/main/resources/db/migration/V0013__init.sql
> +    id2 bigint references users(id)
Да, это я забыл добваить. И фронтендеры говорили мне тоже самое.

2018-05-27 18:33 UTC, Alex-Kuz commented on src/main/java/application/controllers/FriendsController.java
> +        if (allFriendsOfUser == null || allFriendsOfUser.size() == 0) {
годно, согласен

2018-05-27 18:34 UTC, Alex-Kuz commented on src/main/java/application/controllers/FriendsController.java
> +        return null;
Этот сервис просто за несколько часов был на коленке написан, по нашей прихоти. В следующем ПР исправлю.

2018-05-27 18:35 UTC, Alex-Kuz commented on src/main/java/application/dao/implementations/FriendsDAOPostgres.java
> +        final String query = "INSERT INTO friends(id1, id2) VALUES (?,?), (?,?);";
чтобы по 2 не добавлять?

2018-05-27 18:35 UTC, Alex-Kuz commented on src/main/java/application/mechanics/game/GameObject.java
> +public abstract class GameObject {
Хорошо.

2018-05-28 20:12 UTC, KSolovyev commented on src/main/java/application/dao/implementations/FriendsDAOPostgres.java
> +        final String query = "INSERT INTO friends(id1, id2) VALUES (?,?), (?,?);";
нет, чтобы они всегда в одном порядке шли. Удобно же

2018-05-29 06:00 UTC, Alex-Kuz commented on src/main/java/application/dao/implementations/FriendsDAOPostgres.java
> +        final String query = "INSERT INTO friends(id1, id2) VALUES (?,?), (?,?);";
Я не понимаю, зачем? Это ничего не изменит.

2018-05-29 10:08 UTC, Alex-Kuz commented on src/main/java/application/dao/implementations/FriendsDAOPostgres.java
> +        final String query = "INSERT INTO friends(id1, id2) VALUES (?,?), (?,?);";
сейчас только это мешает зыкрыть PR?

2018-05-29 19:19 UTC, KSolovyev commented
здесь все?

2018-05-29 20:34 UTC, merged